### ISSUE TITLE
Sinch 2.0.6 not working with Xcode 12.2

### ISSUE THREAD

**Issue by thocosals2233** [sinch/verification-ios-sdk#2]
I tried many times to integrate Sinch, and there seems to be an issue with the new IOS/Xcode updates. I've used many pods and this is the only one that isnt working. It also appears that this hasnt been updated in a long time.   

I am getting an "Apple Mach-O Linker Error":

Undefined symbols for architecture arm64:
  "protocol descriptor for SinchVerification.Verification", referenced from:
      _symbolic ______pSg 17SinchVerification0B0P in SMSVerificationViewController.o
      _symbolic ______pSg 17SinchVerification0B0P in EnterCodeViewController.o
  "SinchVerification.SMSVerification(_: Swift.String, phoneNumber: Swift.String) -> SinchVerification.Verification", referenced from:
      Aow.SMSVerificationViewController.calloutVerification(Any) -> () in SMSVerificationViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please fix this as it's really affecting our development. For example, 2.0.5 was last updated 3 years ago. https://developers.sinch.com/docs/release-notes-verification-ios-sdk. Or if you guys are planning on closing the business down, please let us know. Thanks.
